CREATE TABLE METEOR_CENTER 
    ( 
     ID_CENTER         NUMBER  NOT NULL , 
     ID_MUN            NUMBER  NOT NULL , 
     DATE_START        TIMESTAMP  NOT NULL , 
     DATE_END          TIMESTAMP  NOT NULL , 
     NAM_CENTER        VARCHAR2 (100)  NOT NULL , 
     COD_CENTER_STAT   VARCHAR2 (2)  NOT NULL , 
     NUM_LATITUDE      NUMBER , 
     NUM_LONGITUDE     NUMBER , 
     NUM_ELEVATION     NUMBER , 
     DATE_OPRTN_INSERT TIMESTAMP  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX METEOR_CENTER_PK ON METEOR_CENTER 
    (ID_CENTER ASC , ID_MUN ASC) ;

ALTER TABLE METEOR_CENTER 
    ADD CONSTRAINT METEOR_CENTER_PK PRIMARY KEY ( ID_CENTER, ID_MUN );

ALTER TABLE METEOR_CENTER 
    ADD CONSTRAINT METEOR_CENTER_FK1 FOREIGN KEY 
    (COD_CENTER_STAT) REFERENCES RU_CENTER_STAT (COD_CENTER_STAT);

ALTER TABLE METEOR_CENTER 
    ADD CONSTRAINT METEOR_CENTER_FK2 FOREIGN KEY (ID_MUN) 
    REFERENCES MUNICIPALITIES (ID_MUN);

CREATE SEQUENCE SECID_CENTER 
START WITH 1 
    MINVALUE 1 
    MAXVALUE 9999 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER TRIG_ID_CENTER 
BEFORE INSERT ON METEOR_CENTER 
FOR EACH ROW 
WHEN (NEW.ID_CENTER IS NULL) 
BEGIN 
    :NEW.ID_CENTER := SECID_CENTER.NEXTVAL; 
END;
/



