CREATE TABLE AUT_COMM 
    ( 
     ID_COMM           NUMBER  NOT NULL ,
     ID_AEMET_COMM     VARCHAR2 (3), 
     NAM_COMM          VARCHAR2 (50) , 
     DATE_OPRTN_INSERT TIMESTAMP  NOT NULL 
    );
CREATE UNIQUE INDEX AUT_COMM_PK ON AUT_COMM 
    (ID_COMM ASC);

ALTER TABLE AUT_COMM 
    ADD CONSTRAINT AUT_COMM_PK PRIMARY KEY (ID_COMM);

CREATE SEQUENCE SECID_COMM 
START WITH 1 
    MINVALUE 1 
    MAXVALUE 99999
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER TRIG_ID_COMM 
BEFORE INSERT ON AUT_COMM 
FOR EACH ROW 
WHEN (NEW.ID_COMM IS NULL) 
BEGIN 
    :NEW.ID_COMM := SECID_COMM.NEXTVAL; 
END;