CREATE TABLE MUNICIPALITIES 
    ( 
     ID_MUN            NUMBER  NOT NULL , 
     ID_PROV           NUMBER  NOT NULL , 
     NAM_MUN           VARCHAR2 (50) , 
     DATE_OPRTN_INSERT TIMESTAMP  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX MUNICIPALITIES_PK ON MUNICIPALITIES 
    (ID_MUN ASC) 
;

ALTER TABLE MUNICIPALITIES 
    ADD CONSTRAINT MUNICIPALITIES_PK PRIMARY KEY (ID_MUN);

ALTER TABLE MUNICIPALITIES 
    ADD CONSTRAINT MUNICIPALITIES_FK1 FOREIGN KEY (ID_PROV) 
    REFERENCES PROVINCE (ID_PROV);

CREATE SEQUENCE SECID_MUN 
START WITH 1 
    MINVALUE 1 
    MAXVALUE 8132 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER TRIG_ID_MUN 
BEFORE INSERT ON MUNICIPALITIES 
FOR EACH ROW 
WHEN (NEW.ID_MUN IS NULL) 
BEGIN 
    :NEW.ID_MUN := SECID_MUN.NEXTVAL; 
END;
/



