CREATE TABLE PROVINCE 
    ( 
     ID_PROV           NUMBER  NOT NULL , 
     ID_COMM           NUMBER  NOT NULL , 
     NAM_PROV          VARCHAR2 (50) , 
     DATE_OPRTN_INSERT TIMESTAMP  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX PROVINCE_PK ON PROVINCE 
    (ID_PROV ASC);

ALTER TABLE PROVINCE 
    ADD CONSTRAINT PROVINCE_PK PRIMARY KEY (ID_PROV) ;

ALTER TABLE PROVINCE 
    ADD CONSTRAINT AUT_COMM_FK1 FOREIGN KEY 
    (ID_COMM) 
    REFERENCES AUT_COMM 
    (ID_COMM);

CREATE SEQUENCE SECID_PROV 
START WITH 1 
    MINVALUE 1 
    MAXVALUE 50 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER TRIG_ID_PROV 
BEFORE INSERT ON PROVINCE 
FOR EACH ROW 
WHEN (NEW.ID_PROV IS NULL) 
BEGIN 
    :NEW.ID_PROV := SECID_PROV.NEXTVAL; 
END;
/



