CREATE TABLE TIME_REPORT 
    ( 
     ID_REPORT         NUMBER  NOT NULL , 
     DATE_REPORT       TIMESTAMP  NOT NULL , 
     ID_CENTER         NUMBER  NOT NULL , 
     ID_MUN            NUMBER  NOT NULL , 
     NUM_TEMP          NUMBER (4,1) , 
     PRCT_HUM          NUMBER , 
     RAIN_FALL         NUMBER (5,1) , 
     WIND_SPEED        NUMBER (3) , 
     ATM_PRESS         NUMBER (5,1) , 
     DATE_OPRTN_INSERT TIMESTAMP  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX TIME_REPORT_PK ON TIME_REPORT 
    (ID_REPORT ASC , DATE_REPORT ASC );

ALTER TABLE TIME_REPORT 
    ADD CONSTRAINT TIME_REPORT_PK PRIMARY KEY (ID_REPORT, DATE_REPORT);

ALTER TABLE TIME_REPORT 
    ADD CONSTRAINT TIME_REPORT_FK1 FOREIGN KEY (ID_CENTER,ID_MUN) 
    REFERENCES METEOR_CENTER (ID_CENTER,ID_MUN);