CREATE TABLE AUT_COMM 
    ( 
     ID_COMM           INT IDENTITY(1,1)  NOT NULL ,
     ID_AEMET_COMM     VARCHAR (3) UNIQUE, 
     NAM_COMM          VARCHAR (50) , 
     DATE_OPRTN_INSERT DATETIME2 DEFAULT GETDATE()  NOT NULL 
    );

ALTER TABLE AUT_COMM 
    ADD CONSTRAINT AUT_COMM_PK PRIMARY KEY (ID_COMM);