CREATE TABLE METEOR_CENTER 
    ( 
     ID_CENTER         INT IDENTITY(1,1)  NOT NULL , 
     ID_MUN            INT  NOT NULL , 
     DATE_START        DATETIME2  NOT NULL , 
     DATE_END          DATETIME2  NOT NULL , 
     NAM_CENTER        VARCHAR (100)  NOT NULL , 
     COD_CENTER_STAT   VARCHAR (2)  NOT NULL , 
     NUM_LATITUDE      INT , 
     NUM_LONGITUDE     INT , 
     NUM_ELEVATION     INT , 
     DATE_OPRTN_INSERT DATETIME2 DEFAULT GETDATE()  NOT NULL 
    ) 
;

ALTER TABLE METEOR_CENTER 
    ADD CONSTRAINT METEOR_CENTER_FK1 FOREIGN KEY 
    (COD_CENTER_STAT) REFERENCES RU_CENTER_STAT (COD_CENTER_STAT);

ALTER TABLE METEOR_CENTER 
    ADD CONSTRAINT METEOR_CENTER_FK2 FOREIGN KEY (ID_MUN) 
    REFERENCES MUNICIPALITIES (ID_MUN);


