CREATE TABLE PROVINCE 
    ( 
     ID_PROV           INT IDENTITY(1,1)  NOT NULL , 
     ID_COMM           INT  NOT NULL , 
     NAM_PROV          VARCHAR (50) UNIQUE , 
     DATE_OPRTN_INSERT DATETIME2 DEFAULT GETDATE()  NOT NULL 
    );

ALTER TABLE PROVINCE 
    ADD CONSTRAINT PROVINCE_PK PRIMARY KEY (ID_PROV) ;

ALTER TABLE PROVINCE 
    ADD CONSTRAINT AUT_COMM_FK1 FOREIGN KEY (ID_COMM) REFERENCES AUT_COMM (ID_COMM);
