CREATE TABLE RU_CENTER_STAT 
    ( 
     COD_CENTER_STAT VARCHAR (2)  NOT NULL , 
     SET_VALUE       VARCHAR (15) 
    ) 
;

ALTER TABLE RU_CENTER_STAT 
    ADD CONSTRAINT RU_CENTER_STAT_PK PRIMARY KEY (COD_CENTER_STAT);



