CREATE TABLE TIME_REPORT 
    ( 
     ID_REPORT         INT IDENTITY(1,1)  NOT NULL , 
     DATE_REPORT       TIMESTAMP  NOT NULL , 
     ID_CENTER         INT  NOT NULL , 
     ID_MUN            INT  NOT NULL , 
     NUM_TEMP          DECIMAL (4,1) , 
     PRCT_HUM          INT , 
     RAIN_FALL         DECIMAL (5,1) , 
     WIND_SPEED        DECIMAL (3) , 
     ATM_PRESS         DECIMAL (5,1) , 
     DATE_OPRTN_INSERT DATETIME2 DEFAULT GETDATE()  NOT NULL 
    ) 
;
ALTER TABLE TIME_REPORT 
    ADD CONSTRAINT TIME_REPORT_PK PRIMARY KEY (ID_REPORT, DATE_REPORT);

ALTER TABLE TIME_REPORT 
    ADD CONSTRAINT TIME_REPORT_FK1 FOREIGN KEY (ID_CENTER,ID_MUN) 
    REFERENCES METEOR_CENTER (ID_CENTER,ID_MUN);